// <auto-generated />
using System;
using BillConductor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillConductor.Infrastructure.Migrations
{
    [DbContext(typeof(BillConductorContext))]
    [Migration("20240229022834_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("BillConductor.Core.HealthCheck.HealthCheck", b =>
                {
                    b.Property<DateTime>("HealthCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("HealthChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
